call pathogen#infect()
call pathogen#helptags()
"Since pathogen is installed - see installation part of:
    "http://mirnazim.org/writings/vim-plugins-i-use/
"All I need to do to install a vim plugin is use the command (while in .vim)
    "git submodule add (the github url of the vim plugin) bundle/[repo_name]
        "ex: git submodule add git://github.com/tpope/vim-fugitive.git bundle/fugitive
    "git submodule init && git submodule update
"BOOM! Installed.

let mapleader="\<Space>"

"General Settings
set nobackup
set nowritebackup
set noswapfile
set scrolloff=4
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set smarttab
set expandtab
set nu
set lbr
set ignorecase
set splitbelow
set cursorline
set smartcase
set hlsearch
set gdefault
set hidden
set backspace=indent,eol,start
set foldmethod=indent
set foldlevel=99
filetype plugin indent on
filetype on
syntax on
colorscheme dracula

"No arrow keys
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
nnoremap j gj
nnoremap k gk
inoremap jj <ESC>

"Plugin Settings
    "Buftabline
    let g:buftabline_indicators=1

    "Syntatic
    set statusline+=%#warningmsg#
    set statusline+=%{SyntasticStatuslineFlag()}
    set statusline+=%*

"Mappings
    "Folding
    nnoremap <leader>f za

    "Spell check
    nnoremap <leader>sc :set spell spelllang=en_us<CR>
    nnoremap <leader>so :set nospell<CR>

    "Buffers
    nnoremap <leader>k <C-w>k
    "nnoremap <leader>l :blast<CR>
    nnoremap <leader>j <C-w>j
    "nnoremap <leader>h :bfirst<CR>
    "nnoremap <leader>c :bdelete<CR>
    "nnoremap <leader>e :edit<Space>

    "Splits
    "nnoremap <leader>sr= :resize +5<CR>
    "nnoremap <leader>sr- :resize -5<CR>
    "nnoremap <leader>sj <C-w>j
    "nnoremap <leader>sk <C-w>k

    "Productivity
    nnoremap <leader>w :w<CR>
    "nnoremap <leader>W :wa<CR>
    nnoremap <leader>q :wq<CR>
    "nnoremap <leader>Q :wqa<CR>
    nnoremap <leader>fq :q!<CR>
    "nnoremap <leader>Fq :qa!<CR>
    nnoremap <leader>rp :! python %<CR>
    nnoremap <leader>u <C-r>
    nnoremap <leader>o :noh<CR>

    "Fugitive
    nnoremap <leader>gs :Gstatus<CR>
    nnoremap <leader>gc :Gcommit<CR>
    nnoremap <leader>ga :Gwrite<CR>
    nnoremap <leader>gb :Gblame<CR>
    nnoremap <leader>gd :Gdiff<CR>
    nnoremap <leader>gp :Git push<CR>

    "Clipboard
    nnoremap <leader>y :<C-u>exec 'normal ' . v:count1 . '"+yy'<CR>
    vnoremap <leader>y "+y
    nnoremap <leader>p :<C-u>exec 'normal ' . v:count1 . '"+p'<CR>
    vnoremap <leader>p "+p

"Bottom bar settings
set noruler
set laststatus=2
set statusline=%<\ %f\ %m%y%=%-35.(Line:\ %l\ of\ %L,\ Col:\ %c%V\ (%P)%)

"Folding plugin
let g:pymode_folding=0
set foldmethod=indent
set foldlevel=99

"Python indenting
au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix |

"JS/HTML/CSS indenting
au BufNewFile,BufRead *.js, *.html, *.css
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2 |
