#!/bin/bash

IN_VISION="$(pwd | grep vision)"
if [[ ! -z ${IN_VISION} ]]; then
    BRANCH="$(git symbolic-ref HEAD | awk -F '/' '{ print $3 }')"
    OTF="$(echo $BRANCH | awk -F '-' '{ print $1 }')"
    OT="$(echo $OTF | awk -F 'f' '{ print $2 }')"

    echo -e "\n\n[otf: $OT]" > template.txt
    git commit -t template.txt $@
    rm template.txt
else
    git commit $@
fi
