#!/bin/bash

IN_VISION="$(pwd | grep vision)"
if [ ! -z ${IN_VISION} ]; then
    branch="$(git symbolic-ref HEAD | awk -F '/' '{ print $3 }')"
    otf="$(echo $branch | awk -F '-' '{ print $1 }')"
    ot="$(echo $otf | awk -F 'f' '{ print $2 }')"

    echo -e "\n\n[otf: $ot]" > template.txt
    git commit -t template.txt $@
    rm template.txt
else
    git commit $@
fi
